"""change User field

Revision ID: 5c767a4ca1fd
Revises: 9fbdd7e8da56
Create Date: 2025-05-15 15:30:43.160544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c767a4ca1fd'
down_revision = '9fbdd7e8da56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
